FROM apache/airflow:2.9.3

USER root
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    libabsl-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt -c https://raw.githubusercontent.com/apache/airflow/constraints-2.9.3/constraints-3.10.txt